"""
Caradonna-Tung rotor — HOVER, Cumulant + ALM + MLG.  ALM thrust/loading validation.

Classic hover benchmark (Caradonna & Tung, NASA TM-81232, 1981):
  - 2 blades, NACA0012, UNTWISTED, rectangular, aspect ratio R/c = 6
  - R = 1.143 m, constant chord c = 0.1905 m, solidity sigma = 2c/(pi R) = 0.106
  - Standard validation point: collective 8 deg, M_tip = 0.439, ~1250 RPM
  - Sea-level standard air: a = 340.3 m/s, rho = 1.225, nu = 1.461e-5

What we validate (ALM limits):
  The experiment's primary data is BLADE-SURFACE PRESSURE Cp, which an ALM
  (a force LINE, no surface) cannot reproduce.  ALM-comparable quantities:
    - integrated thrust C_T  (vs experiment / many reproductions)
    - spanwise loading  dC_T/dr  /  sectional C_n  (blade_diagnostics CSV)
  No torque was measured -> no Figure of Merit from this case.

Airfoil: constant chord -> reuse the constant-chord Re->Mach closure with a
Mach-indexed NACA0012 deck generated by NeuralFoil+Viterna
(data/airfoils/NACA0012.C81, via src/actuator/c81_from_neuralfoil.py).
No ALM code change needed.  Scaling: convective (u_max=0.1), like HART-II.
"""
import os

import numpy as np

# =============================================================================
# S1. PHYSICAL CONSTANTS (Caradonna-Tung)
# =============================================================================
R_PHYS      = 1.143                                 # [m]
D_PHYS      = 2.0 * R_PHYS                           # [m] = 2.286
CHORD_PHYS  = 0.1905                                 # [m] constant
N_BLADES    = 2
ROOT_CUT_RR = 0.20                                   # aero root cutout (cuff)
SIGMA       = N_BLADES * CHORD_PHYS / (np.pi * R_PHYS)   # 0.1061

RHO_PHYS    = 1.225                                  # [kg/m^3] sea level
C_S_PHYS    = 340.3                                  # [m/s]
NU_PHYS     = 1.461e-5                               # [m^2/s]

RPM         = 1250
OMEGA_PHYS  = RPM * 2.0 * np.pi / 60.0               # [rad/s] = 130.9
TIP_SPEED   = OMEGA_PHYS * R_PHYS                    # [m/s] = 149.6
M_TIP       = TIP_SPEED / C_S_PHYS                   # 0.4396 ~ 0.439
RE_75       = 0.75 * TIP_SPEED * CHORD_PHYS / NU_PHYS

_HERE       = os.path.dirname(os.path.abspath(__file__))
_REPO       = os.path.abspath(os.path.join(_HERE, "..", ".."))
# Authoritative NACA0012 Mach deck (Prof. Yee, Cl+Cd) converted from
# aeromechanics_workshop/CT_rotor_datas/ via convert_yee_to_c81.py.
# Preferred over the NeuralFoil-generated deck (which over-predicts CL_max ~11%
# and under-predicts CD ~30% -- see temp_results/naca0012_yee_vs_neuralfoil.png).
C81_PATH    = os.path.join(_REPO, "data", "airfoils", "NACA0012_Yee.C81")

N_RADIAL    = 40

# Grid presets.  MEMORY (empirical, from two 24 GB-GPU OOMs):
#   ~410 bytes/cell -- dominated by the LBM/MLG structure; SGS adds only
#   ~12 B/cell (NOT the driver).  On a ~24 GB GPU the cell count is the limit:
#     light    (30M)  ~13 GB -> fits
#     medium   (43M)  ~18 GB -> fits  (finest that fits 24 GB)
#     balanced (60M)  ~25 GB -> OOM (both SGS on and off)
GRID_PRESETS = {
    "balanced": (40, [(0.75, 2.5, 1.25), (0.4, 1.0, 0.75), (0.15, 0.25, 0.6)]),
    "medium":   (36, [(0.75, 2.5, 1.25), (0.4, 1.0, 0.75), (0.15, 0.25, 0.6)]),
    "light":    (32, [(0.75, 2.5, 1.25), (0.4, 1.0, 0.75), (0.15, 0.25, 0.6)]),
    "lighter":  (28, [(0.75, 2.5, 1.25), (0.4, 1.0, 0.75), (0.15, 0.25, 0.6)]),
    # EXTENDED fine regions at the SAME dx as 'light' (D=32) -> isolates the
    # fine-region EXTENT from dx.  The finest level now follows the descending,
    # contracting tip vortex (downstream 0.25D->1.0D, lateral 0.6D->0.7D) so the
    # tip-induced downwash is no longer cut off.  ~80M cells (~33 GB) -> DGX only.
    "extended": (32, [(1.0, 3.5, 1.6), (0.5, 2.0, 1.0), (0.2, 1.0, 0.7)]),
}
DEFAULT_PRESET = "light"
BYTES_PER_CELL = 410.0        # empirical (SGS on or off; cell count is the limit)


def _sections(collective_deg):
    """Untwisted: every active station at twist = collective; NACA0012."""
    rR = [ROOT_CUT_RR, 0.30, 0.40, 0.50, 0.60, 0.68, 0.75,
          0.80, 0.89, 0.95, 0.96, 1.00]
    secs = [(0.0, CHORD_PHYS, collective_deg, "naca0012", False)]
    for x in rR:
        secs.append((x * R_PHYS, CHORD_PHYS, collective_deg, "naca0012", True))
    return secs


def build_config(collective_deg=8.0, mtip=0.439, smoke=False,
                 smoke_sgs=False, preset=None, use_sgs=True):
    if smoke:
        D, EXTENTS, DEVICE, N_REV = 16, [(0.5, 1.5, 1.0)], "cpu", 1
        USE_SGS = smoke_sgs
    else:
        preset_name = preset or DEFAULT_PRESET
        D, EXTENTS = GRID_PRESETS[preset_name]
        DEVICE, N_REV, USE_SGS = "gpu", 18, use_sgs
    NUM_LEVELS = len(EXTENTS) + 1
    U_MAX_LU = 0.1
    STEPS_REV = int(round(np.pi * D / U_MAX_LU))
    RHO_LU = 1.0

    # tip Mach sets the rotor speed (sea-level a).  M=0.439 and 0.877 are the
    # two classic Caradonna-Tung pressure-survey cases.
    tip_speed = mtip * C_S_PHYS                # [m/s]
    omega = tip_speed / R_PHYS                 # [rad/s]
    rpm = omega * 60.0 / (2.0 * np.pi)

    Nx, Ny, Nz = 8 * D, 5 * D, 5 * D
    HUB_X, HUB_Y, HUB_Z = 3 * D, Ny // 2, Nz // 2

    def _box(up, down, lat):
        return {"x_min": HUB_X - int(up * D),  "x_max": HUB_X + int(down * D),
                "y_min": HUB_Y - int(lat * D), "y_max": HUB_Y + int(lat * D),
                "z_min": HUB_Z - int(lat * D), "z_max": HUB_Z + int(lat * D)}

    levels = [{}] + [{"region": _box(*e)} for e in EXTENTS]

    simulation = {"device_mode": DEVICE, "precision": "float32",
                  "dimension": 3, "lattice_model": "D3Q27",
                  "collision_model": "cumulant"}
    physics = {"rho": RHO_PHYS, "U_inf": 0.0, "nu": NU_PHYS,
               "L_char": D_PHYS, "flow_direction": [1.0, 0.0, 0.0]}
    grid = {"Nx": Nx, "Ny": Ny, "Nz": Nz, "resolution": D}
    numerics = {"acoustic_scaling": False, "u_max": U_MAX_LU,
                "c_s_phys": C_S_PHYS, "collision": "cumulant"}
    boundaries = {
        "xmin": {"location": "xmin", "method": "eq", "velocity": [0.0, 0.0, 0.0]},
        "xmax": {"location": "xmax", "method": "sponge", "velocity": [0.0, 0.0, 0.0],
                 "density": RHO_LU, "thickness": 20, "strength": 0.1},
        "ymin": {"location": "ymin", "method": "eq", "velocity": [0.0, 0.0, 0.0]},
        "ymax": {"location": "ymax", "method": "eq", "velocity": [0.0, 0.0, 0.0]},
        "zmin": {"location": "zmin", "method": "eq", "velocity": [0.0, 0.0, 0.0]},
        "zmax": {"location": "zmax", "method": "eq", "velocity": [0.0, 0.0, 0.0]},
    }
    airfoil_polar = {"method": "c81", "path": C81_PATH, "chord": CHORD_PHYS,
                     "nu": NU_PHYS, "sound_speed": C_S_PHYS}
    actuator_line = {
        "enabled": True,
        "rotor": {
            "rpm": rpm, "radius": R_PHYS, "omega": omega,
            "n_blades": N_BLADES, "hub_center": [HUB_X, HUB_Y, HUB_Z],
            "rotation_axis": [1, 0, 0], "thrust_direction": [-1, 0, 0],
            "theta_0": 0.0,
            "blade": {"sections": [
                {"r": float(r), "chord": float(c), "twist": float(t),
                 "airfoil": af, "active": act}
                for r, c, t, af, act in _sections(collective_deg)]},
            "grid": {"n_radial": N_RADIAL},
        },
        "gaussian_cutoff": 3.0, "rho_ref": 1.0, "coeff_mode": "rotorcraft",
        "ramp_steps": STEPS_REV, "prandtl_loss": True,
    }
    mlg = {"enabled": True, "num_levels": NUM_LEVELS, "overlap_width": 2,
           "interpolation": "cubic", "filter_level": 1, "levels": levels}
    sgs = ({"enabled": True, "model": "dyn_smag"} if USE_SGS
           else {"enabled": False, "model": "off"})
    time = {"max_steps": N_REV * STEPS_REV, "output_interval": STEPS_REV,
            "logging_interval": max(1, STEPS_REV // 20),
            "checkpoint_interval": 5 * STEPS_REV,
            "conservation_interval": max(1, STEPS_REV // 2)}
    tag = "smoke" if smoke else "mlg%d_D%d_%s" % (NUM_LEVELS, D, preset_name)
    if not smoke and not USE_SGS:
        tag += "_nosgs"
    folder = "result_ct_t%04.1f_M%03d_%s" % (collective_deg, round(mtip * 1000), tag)
    output = {"output_dir": "./%s/vtk" % folder,
              "checkpoint_dir": "./%s/checkpoints" % folder,
              "csv_dir": "./%s/csv" % folder, "clear_previous": True,
              "vtk": {"enabled": True, "precision": "float32",
                      "variables": ["density", "pressure", "velocity",
                                    "velocity_magnitude"]},
              "checkpoint": {"enabled": True, "keep_last_n": 2}}
    return {"simulation": simulation, "physics": physics, "grid": grid,
            "numerics": numerics, "boundaries": boundaries,
            "internal_geometry": {"type": "none"}, "mlg": mlg, "sgs": sgs,
            "airfoil_polar": airfoil_polar, "actuator_line": actuator_line,
            "conservation": {"enabled": True, "verbose": 0, "log_to_csv": True},
            "convergence": {"enabled": False},
            "force_calculation": {"enabled": False}, "output": output,
            "time": time}


if __name__ == "__main__":
    print("  [Caradonna-Tung HOVER — ALM validation]")
    print("  R=%.3f m, c=%.4f m, %d blades, untwisted, sigma=%.3f"
          % (R_PHYS, CHORD_PHYS, N_BLADES, SIGMA))
    print("  RPM=%d, V_tip=%.1f m/s, M_tip=%.4f, Re_0.75R=%.2e"
          % (RPM, TIP_SPEED, M_TIP, RE_75))
    print("  C81: %s (exists=%s)" % (C81_PATH, os.path.exists(C81_PATH)))
    cfg = build_config(8.0)
    print("  grid L0=%dx%dx%d, %d-level, steps/rev~%d, max_steps=%d"
          % (cfg["grid"]["Nx"], cfg["grid"]["Ny"], cfg["grid"]["Nz"],
             cfg["mlg"]["num_levels"],
             int(round(np.pi * cfg["grid"]["resolution"] / 0.1)),
             cfg["time"]["max_steps"]))
