"""
HART-II rotor — HOVER, Cumulant + ALM + MLG.  Aeromechanics Workshop 2026, Task 3.

Shared config builder. Per-collective configs import `build_config()`:

    import sys, os
    sys.path.insert(0, os.path.dirname(__file__))
    from _hart2_hover_base import build_config
    config = build_config(collective_deg=8.0)        # production
    # config = build_config(collective_deg=8.0, smoke=True)   # CPU pipeline test

Task 3 deliverable: Figure of Merit vs C_T/sigma, generated by an OPEN-LOOP
collective sweep (3..16 deg).  FM = C_T^1.5 / (sqrt(2) * C_P).

=================================  PHYSICS  ===================================
HART-II rotor (all geometry from HART2_structural_property.xlsx "로터 모델링
데이터" block):
  - 4 blades, rotation CCW, R = 2.0 m, rectangular chord c = 0.121 m
  - linear twist -8 deg/R (washout), referenced to 0.75R
  - aerodynamic root cutout 0.44 m (r/R = 0.22)
  - airfoil NACA23012 (with tab) over the full span  -> NACA23012.C81 deck
  - RPM = 1041  (Omega = 109.0 rad/s, V_tip = 218.0 m/s)
  - solidity sigma = N c / (pi R) = 0.077
Atmosphere (workshop): rho = 1.2055 kg/m^3, T = 17.3 C
  -> a = 341.6 m/s, nu ~ 1.50e-5 m^2/s (Sutherland mu/rho); Re_0.75R ~ 1.3e6.

  *** PRECONE (coning) = 2.5 deg is NOT applied: the current ALM has no precone
      support (verified: no precone/coning in src/actuator/).  Effect on thrust
      is ~cos^2(2.5 deg) ~ 0.2% — negligible for a first FM curve.  Flagged for
      a possible future ALM extension. ***

==============================  WHY THESE CHOICES  ============================
Weak-compressibility & Mach.  The blade-relative tip Mach is 0.638, but in an
ALM the LBM grid never carries the section velocity — it resolves only the
low-Mach induced/wake field (M ~ 0.03-0.05 in hover).  The transonic blade
aerodynamics live entirely in the Mach-interpolated C81 lookup (airfoil_polar
method "c81").  See src/actuator/c81_loader.py.

Scaling.  CONVECTIVE (acoustic_scaling=False, u_max=0.1), NOT acoustic.
Acoustic scaling would map V_tip to u_max = V_tip/(c_s*sqrt3) = 0.368, which
exceeds the "u_max > 0.1 destabilises ALM forcing" threshold noted in prior ALM
work.  FM needs correct loads, not acoustic accuracy, so convective is the
robust choice.  The C81 Mach recovery (M = nu/(c*a)*Re) is scaling-invariant,
so loads stay correct either way.

Turbulence.  Re_0.75R ~ 1.3e6 -> WALE SGS on the resolved wake (Cumulant alone
is stable but adds numerical dissipation).  Toggle in `build_config`.
"""

import os

import numpy as np

# =============================================================================
# S1. PHYSICAL CONSTANTS (HART-II, confirmed)
# =============================================================================
R_PHYS      = 2.0                                  # [m] rotor radius
D_PHYS      = 2.0 * R_PHYS                          # [m] diameter = 4.0
CHORD_PHYS  = 0.121                                 # [m] constant chord
N_BLADES    = 4
ROOT_CUT_R  = 0.44                                  # [m] aero root cutout
ROOT_CUT_RR = ROOT_CUT_R / R_PHYS                   # = 0.22
TWIST_RATE  = -8.0                                  # [deg/R] linear washout
TWIST_REF   = 0.75                                  # collective defined @ 0.75R
PRECONE_DEG = 2.5                                   # [deg] NOT applied (see header)

RPM         = 1041
OMEGA_PHYS  = RPM * 2.0 * np.pi / 60.0              # [rad/s] = 109.0
TIP_SPEED   = OMEGA_PHYS * R_PHYS                   # [m/s]   = 218.0
SIGMA       = N_BLADES * CHORD_PHYS / (np.pi * R_PHYS)   # solidity = 0.077

RHO_PHYS    = 1.2055                                # [kg/m^3]
C_S_PHYS    = 341.6                                 # [m/s] sound speed @ 17.3 C
NU_PHYS     = 1.50e-5                               # [m^2/s] mu_Sutherland/rho

RE_75       = 0.75 * TIP_SPEED * CHORD_PHYS / NU_PHYS    # ~1.32e6
M_TIP       = TIP_SPEED / C_S_PHYS                       # 0.638

# C81 deck. Primary copy lives in data/airfoils/ (the tree that IS deployed
# to the cluster alongside src/ and configs/ — aeromechanics_workshop/ is
# not synced, which broke the 2026-07-23 cluster launch). The original
# references/ location is kept as a local fallback.
_HERE       = os.path.dirname(os.path.abspath(__file__))
_REPO       = os.path.abspath(os.path.join(_HERE, "..", ".."))
_C81_CANDIDATES = [
    os.path.join(_REPO, "data", "airfoils", "hart2", "NACA23012.C81"),
    os.path.join(_REPO, "aeromechanics_workshop", "references",
                 "Z01_data", "NACA23012.C81"),
]
C81_PATH    = next((p for p in _C81_CANDIDATES if os.path.exists(p)),
                   _C81_CANDIDATES[0])

N_RADIAL    = 40                                    # markers per blade


# =============================================================================
# S2. BLADE SECTIONS  (constant chord, linear twist folded with collective)
# =============================================================================
def _twist_deg(r_over_R: float, collective_deg: float) -> float:
    """Geometric pitch at r/R: collective (at 0.75R) + linear -8 deg/R washout."""
    return collective_deg + TWIST_RATE * (r_over_R - TWIST_REF)


def _blade_sections(collective_deg: float):
    """List of (r[m], chord[m], twist[deg], airfoil, active).

    One inactive hub station at r=0; active stations from the root cutout
    (r/R=0.22) to the tip.  Linear interpolation reproduces exactly the
    constant chord + linear twist between stations.
    """
    rR_active = [0.22, 0.30, 0.40, 0.50, 0.60, 0.70, 0.75,
                 0.80, 0.85, 0.90, 0.95, 1.00]
    secs = [(0.0, CHORD_PHYS, _twist_deg(0.0, collective_deg),
             "naca23012", False)]
    for rR in rR_active:
        secs.append((rR * R_PHYS, CHORD_PHYS,
                     _twist_deg(rR, collective_deg), "naca23012", True))
    return secs


# =============================================================================
# S3. GRID PRESETS (sized for GPU memory; ~213 bytes/cell incl. f-buffers)
# =============================================================================
# Cost is dominated by the FINE-level lateral extent (~lateral^2), NOT the
# number of levels.  Tightening the fine regions onto the disk keeps the blade
# resolution (chord_fine) while cutting memory.  Each entry:
#     (D_on_L0, [(up, down, lat) per fine level in D-units])
# Approx totals (OverlapManager) / persistent GB / chord_fine [cells]:
GRID_PRESETS = {
    "balanced": (40, [(0.75, 2.5, 1.25), (0.4, 1.0, 0.75), (0.15, 0.25, 0.6)]),
    #            ~60M / ~12.8 GB / chord_fine 9.7  -- best fidelity that fits 24 GB
    "light":    (32, [(0.75, 2.5, 1.25), (0.4, 1.0, 0.75), (0.15, 0.25, 0.6)]),
    #            ~30M / ~6.5 GB  / chord_fine 7.7  -- SAFE default for ~24 GB GPU
    "lighter":  (28, [(0.75, 2.5, 1.25), (0.4, 1.0, 0.75), (0.15, 0.25, 0.6)]),
    #            ~21M / ~4.4 GB  / chord_fine 6.8  -- minimal; smaller GPUs
    "full":     (40, [(1.0, 3.0, 1.5), (0.5, 1.5, 1.0), (0.25, 0.5, 0.8)]),
    #            ~136M / ~29 GB  / chord_fine 9.7  -- needs a 32 GB+ GPU
    # farfield40_mlg4 (2026-07-23): the HVAB farfield40_mlg4 D-relative
    # geometry transplanted (radial 6R / up 3R / down 10R domain, 4 levels,
    # ALM on L3, dx_fine = D_PHYS/320 = 12.5 mm, chord_fine 9.7 cells).
    # Same relative nesting as the validated HVAB campaign grid; ~65M cells,
    # esoteric 4-rank ~3.4 GB/GPU. A len-3 entry carries a DOMAIN override
    # (nx/ny/nz in D units + hub_x) replacing the default 8D x 5D x 5D box.
    "farfield40_mlg4": (40,
                        [(0.65625, 1.84375, 1.15625),
                         (0.4,     1.0,     0.84375),
                         (0.125,   0.25,    0.6875)],
                        {"nx_D": 6.5, "ny_D": 6.0, "nz_D": 6.0, "hub_x_D": 1.5}),
}
DEFAULT_PRESET = "light"   # safe for ~24 GB; switch to "balanced" if it fits
BYTES_PER_CELL = 213.0     # empirical (D3Q27 f-buffers dominate)


# =============================================================================
# S3b. CONFIG BUILDER
# =============================================================================
def build_config(collective_deg: float, smoke: bool = False,
                 smoke_sgs: bool = False, preset: str = None,
                 use_sgs: bool = True, eps_correction=None,
                 prandtl_loss=True, sampling=None,
                 radial_truncation: bool = False, n_radial: int = None,
                 n_rev: int = 18, run_tag: str = "",
                 marker_distribution: str = "uniform") -> dict:
    """Assemble the full HART-II hover config for a given collective pitch.

    Args:
        collective_deg: collective pitch at 0.75R [deg] (sweep variable, 3..16)
        smoke:          True -> small CPU grid + few steps (pipeline test only)
        smoke_sgs:      in smoke mode, also enable the SGS model (verify SGS
                        integration); ignored for production (always on).
        preset:         grid preset name (see GRID_PRESETS); default DEFAULT_PRESET.

    2026-07-23 extension (HVAB-parity kwargs, defaults keep every pre-existing
    config bit-identical):
        use_sgs:            False -> SGS off (folder gains "_nosgs")
        eps_correction:     None|dict — Kleine/Dag smearing correction block,
                            passed through to actuator_line["eps_correction"]
        prandtl_loss:       bool|dict — legacy bool, or the full dict form
                            {"enabled","model","g","tip","root","eps_offset"}
        sampling:           None|dict — velocity sampler override
        radial_truncation:  True -> Merabet tip/root truncation+renorm
        n_radial:           markers/blade override (default N_RADIAL=40)
        n_rev:              production revolutions (default 18)
        run_tag:            appended to the result folder name
        marker_distribution: "uniform" (default) | "cosine"
    """
    # --- grid / MLG resolution -------------------------------------------
    _DOM = None
    if smoke:
        D          = 16            # cells per diameter on L0 (small, fast CPU)
        EXTENTS    = [(0.5, 1.5, 1.0)]   # 1 fine level around the disk
        DEVICE     = "cpu"
        N_REV      = 1
        USE_SGS    = smoke_sgs
    else:
        _pv = GRID_PRESETS[preset or DEFAULT_PRESET]
        if len(_pv) == 3:          # (D, EXTENTS, DOMAIN-override)
            D, EXTENTS, _DOM = _pv
        else:
            D, EXTENTS = _pv
        DEVICE     = "gpu"
        N_REV      = n_rev
        USE_SGS    = use_sgs
    NUM_LEVELS = len(EXTENTS) + 1

    U_MAX_LU   = 0.1                                   # convective scaling
    STEPS_REV  = int(round(np.pi * D / U_MAX_LU))      # tip travels pi*D per rev
    RHO_LU     = 1.0

    # --- domain (hover): suction side (-x, up) 3D, wake (+x, down) 5D -----
    # A len-3 preset overrides the box with its DOMAIN dict (D units).
    if _DOM is not None:
        Nx = int(round(_DOM["nx_D"] * D))
        Ny = int(round(_DOM["ny_D"] * D))
        Nz = int(round(_DOM["nz_D"] * D))
        HUB_X = int(round(_DOM["hub_x_D"] * D))
    else:
        Nx = 8 * D
        Ny = 5 * D
        Nz = 5 * D
        HUB_X = 3 * D                                  # 3D below xmin inlet
    HUB_Y = Ny // 2
    HUB_Z = Nz // 2

    # --- MLG fine regions (disk radius = 0.5D in y,z; wake along +x) ------
    # Sized to contain the disk + tip-vortex roll-up + Gaussian spread.
    def _box(up, down, lat):
        return {"x_min": HUB_X - int(up * D),  "x_max": HUB_X + int(down * D),
                "y_min": HUB_Y - int(lat * D), "y_max": HUB_Y + int(lat * D),
                "z_min": HUB_Z - int(lat * D), "z_max": HUB_Z + int(lat * D)}

    region_specs = [None] + [_box(*e) for e in EXTENTS]
    levels = [{} if r is None else {"region": r} for r in region_specs]

    # --- blocks ----------------------------------------------------------
    simulation = {
        "device_mode":     DEVICE,
        "precision":       "float32",
        "dimension":       3,
        "lattice_model":   "D3Q27",
        "collision_model": "cumulant",
    }

    physics = {
        "rho":            RHO_PHYS,
        "U_inf":          0.0,                       # HOVER
        "nu":             NU_PHYS,
        "L_char":         D_PHYS,
        "flow_direction": [1.0, 0.0, 0.0],
    }

    grid = {"Nx": Nx, "Ny": Ny, "Nz": Nz, "resolution": D}

    numerics = {
        "acoustic_scaling": False,                   # convective (see header)
        "u_max":            U_MAX_LU,
        "c_s_phys":         C_S_PHYS,                # physical a (documentation)
        "collision":        "cumulant",
    }

    # Quiescent far-field; wake exits +x through a sponge. eq/sponge only.
    boundaries = {
        "xmin": {"location": "xmin", "method": "eq", "velocity": [0.0, 0.0, 0.0]},
        "xmax": {"location": "xmax", "method": "sponge",
                 "velocity": [0.0, 0.0, 0.0], "density": RHO_LU,
                 "thickness": 20, "strength": 0.1},
        "ymin": {"location": "ymin", "method": "eq", "velocity": [0.0, 0.0, 0.0]},
        "ymax": {"location": "ymax", "method": "eq", "velocity": [0.0, 0.0, 0.0]},
        "zmin": {"location": "zmin", "method": "eq", "velocity": [0.0, 0.0, 0.0]},
        "zmax": {"location": "zmax", "method": "eq", "velocity": [0.0, 0.0, 0.0]},
    }

    # NACA23012 Mach-indexed C81 deck (Re->Mach recovered in the closure).
    airfoil_polar = {
        "method":      "c81",
        "path":        C81_PATH,
        "chord":       CHORD_PHYS,
        "nu":          NU_PHYS,
        "sound_speed": C_S_PHYS,
    }

    actuator_line = {
        "enabled": True,
        "rotor": {
            "rpm":              RPM,
            "radius":           R_PHYS,
            "omega":            OMEGA_PHYS,
            "n_blades":         N_BLADES,
            "hub_center":       [HUB_X, HUB_Y, HUB_Z],   # L0 lattice units
            "rotation_axis":    [1, 0, 0],               # CCW about +x
            "thrust_direction": [-1, 0, 0],              # thrust toward -x (up)
            "theta_0":          0.0,
            "blade": {
                "sections": [
                    {"r": float(r), "chord": float(c), "twist": float(tw),
                     "airfoil": af, "active": act}
                    for r, c, tw, af, act in _blade_sections(collective_deg)
                ],
            },
            "grid": {"n_radial": N_RADIAL if n_radial is None else int(n_radial),
                     # loader default is "uniform" (rotor.py) — key omitted
                     # then, so pre-existing configs stay dict-identical
                     **({"marker_distribution": marker_distribution}
                        if marker_distribution != "uniform" else {})},
        },
        "gaussian_cutoff": 3.0,
        "rho_ref":         1.0,
        "coeff_mode":      "rotorcraft",             # C_T, C_P, FM convention
        "ramp_steps":      STEPS_REV,                # ramp forcing over ~1 rev
        "prandtl_loss":    prandtl_loss,             # bool (legacy) or dict
    }
    if eps_correction is not None:
        actuator_line["eps_correction"] = eps_correction
    if sampling is not None:
        actuator_line["sampling"] = sampling
    if radial_truncation:
        actuator_line["spreading"] = {"radial_truncation": True}

    mlg = {
        "enabled":       True,
        "num_levels":    NUM_LEVELS,
        "overlap_width": 2,
        "interpolation": "cubic",
        "filter_level":  1,
        "levels":        levels,
    }

    # Dynamic Smagorinsky (Germano) — Cs computed locally, clamped to Cs_max;
    # Cs_max / alpha_sq use validated defaults from src/turbulence/sgs.py.
    sgs = ({"enabled": True, "model": "dyn_smag"} if USE_SGS
           else {"enabled": False, "model": "off"})

    time = {
        "max_steps":             N_REV * STEPS_REV,
        "output_interval":       STEPS_REV,
        "logging_interval":      max(1, STEPS_REV // 20),
        "checkpoint_interval":   5 * STEPS_REV,
        "conservation_interval": max(1, STEPS_REV // 2),
    }

    conservation      = {"enabled": True, "verbose": 0, "log_to_csv": True}
    convergence       = {"enabled": False}
    force_calculation = {"enabled": False}

    tag = "smoke" if smoke else "mlg%d_D%d" % (NUM_LEVELS, D)
    if not smoke and not USE_SGS:
        tag += "_nosgs"
    if run_tag:
        tag += "_" + run_tag       # keep variant runs out of baseline folders
    folder = "result_hart2_hover_c%04.1f_%s" % (collective_deg, tag)

    output = {
        "output_dir":     "./%s/vtk" % folder,
        "checkpoint_dir": "./%s/checkpoints" % folder,
        "csv_dir":        "./%s/csv" % folder,
        "clear_previous": True,
        "vtk":            {"enabled": True, "precision": "float32",
                           "variables": ["density", "pressure", "velocity",
                                         "velocity_magnitude"]},
        "checkpoint":     {"enabled": True, "keep_last_n": 2},
    }

    return {
        "simulation":        simulation,
        "physics":           physics,
        "grid":              grid,
        "numerics":          numerics,
        "boundaries":        boundaries,
        "internal_geometry": {"type": "none"},
        "mlg":               mlg,
        "sgs":               sgs,
        "airfoil_polar":     airfoil_polar,
        "actuator_line":     actuator_line,
        "conservation":      conservation,
        "convergence":       convergence,
        "force_calculation": force_calculation,
        "output":            output,
        "time":              time,
    }


# =============================================================================
# S4. STANDALONE — parameter + memory summary (per preset)
# =============================================================================
def _estimate_cells(cfg):
    """Total MLG node count via OverlapManager (exact), + approx GB."""
    import sys
    sys.path.insert(0, _REPO)
    from src.grid.overlap_manager import OverlapManager, IndexBox
    from src.grid.level_scaling import LevelScaler
    g, m = cfg["grid"], cfg["mlg"]
    Nx, Ny, Nz = g["Nx"], g["Ny"], g["Nz"]
    scaler = LevelScaler(tau_0=0.503, num_levels=m["num_levels"])
    mgr = OverlapManager()
    coarse = (Nx, Ny, Nz); origins = [(0, 0, 0)]; spac = [(1, 1, 1)]
    tot = Nx * Ny * Nz; per = [tot]
    for k in range(1, m["num_levels"]):
        rc = m["levels"][k]["region"]; po, pd = origins[k - 1], spac[k - 1]
        fr = IndexBox(round((rc["x_min"] - po[0]) / pd[0]), round((rc["x_max"] - po[0]) / pd[0]),
                      round((rc["y_min"] - po[1]) / pd[1]), round((rc["y_max"] - po[1]) / pd[1]),
                      round((rc["z_min"] - po[2]) / pd[2]), round((rc["z_max"] - po[2]) / pd[2]))
        reg = mgr.add_level_pair(coarse, fr, m["overlap_width"])
        fdc = reg.fine_domain_coarse; lu = scaler.get_level_units(k)
        origins.append((po[0] + fdc.x_start * pd[0], po[1] + fdc.y_start * pd[1],
                        po[2] + fdc.z_start * pd[2]))
        spac.append((lu.dx,) * 3); fs = reg.fine_shape
        n = fs[0] * fs[1] * fs[2]; tot += n; per.append(n); coarse = fs
    return tot, per


if __name__ == "__main__":
    print("  [HART-II HOVER — Task 3]")
    print("  R=%.1f m, c=%.3f m, %d blades, RPM=%d, sigma=%.3f"
          % (R_PHYS, CHORD_PHYS, N_BLADES, RPM, SIGMA))
    print("  V_tip=%.1f m/s, M_tip=%.3f, Re_0.75R=%.2e"
          % (TIP_SPEED, M_TIP, RE_75))
    print("  twist=%.1f deg/R @ %.2fR ref, root cut r/R=%.2f, precone=%.1f deg (N/A)"
          % (TWIST_RATE, TWIST_REF, ROOT_CUT_RR, PRECONE_DEG))
    print("  C81: exists=%s\n" % os.path.exists(C81_PATH))
    print("  preset      D  lvls    cells     ~GB  chord_fine  steps/rev")
    for name in ("lighter", "light", "balanced", "full"):
        cfg = build_config(8.0, preset=name)
        tot, _ = _estimate_cells(cfg)
        D = cfg["grid"]["resolution"]; nl = cfg["mlg"]["num_levels"]
        dx_fine = (D_PHYS / D) / (2 ** (nl - 1))
        mark = "  <- default" if name == DEFAULT_PRESET else ""
        print("  %-9s %3d  %3d  %10s  %5.1f   %5.1f      %5d%s"
              % (name, D, nl, "%.1fM" % (tot / 1e6),
                 tot * BYTES_PER_CELL / 1e9, CHORD_PHYS / dx_fine,
                 int(round(np.pi * D / 0.1)), mark))
    print("\n  default='%s'  (edit DEFAULT_PRESET or pass preset= to build_config)"
          % DEFAULT_PRESET)
